Repository WordPress/Requests, pull requests merged in 2020-10, with the labels that each got.

#386 Fix PHP cross-version compatibility issue (PHP 7)
  library/Requests.php
Labels: Transports

#263 Nits on phpdoc, use of internal methods with unexpected type
  library/Requests/Cookie.php
  library/Requests/Cookie/Jar.php
  library/Requests/IRI.php
  library/Requests/Response/Headers.php
  library/Requests/Transport/cURL.php
  library/Requests/Transport/fsockopen.php
  library/Requests/Utility/CaseInsensitiveDictionary.php
Labels: Documentation

#366 Tests: enable the `Encoding` tests
  tests/phpunit.xml.dist
Labels: Testing

#363 CS: remove stray debug code
  tests/Transport/Base.php
Labels: Testing

#359 QA: remove dead code
  tests/phpunit6-compat.php
Labels: Testing

#311 verify => false does not work with fsockopen
  library/Requests/Transport/fsockopen.php
  tests/Transport/Base.php
Labels: Transports

#368 Add Content-* headers for empty POST requests
  library/Requests/Transport/fsockopen.php
  tests/Transport/Base.php
  tests/Transport/fsockopen.php
Labels: Transports

#412 Tests: verify exception messages
  tests/Auth/Basic.php
  tests/Cookies.php
  tests/IDNAEncoder.php
  tests/Proxy/HTTP.php
  tests/Requests.php
  tests/Response/Headers.php
  tests/Transport/Base.php
  tests/Transport/cURL.php
  tests/Transport/fsockopen.php
Labels: Testing
