Repository WordPress/Requests, pull requests merged in 2021-06, with the labels that each got.

#484 Add misc. files to gitattributes
  .gitattributes
Labels: Type: testing/chores/QA

#483 Add a release checklist
  .github/release-checklist.md
Labels: Type: documentation, Type: meta

#485 Requests::Version: update version number
  .gitattributes
  library/Requests.php
Labels: Type: bug, Type: meta

#486 Changelog for release 1.8.1
  CHANGELOG.md
Labels: Type: documentation, Type: meta

#470 Drop support for PHP < 5.6 & PEAR
  .gitattributes
  .github/workflows/lint.yml
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
  .phpcs.xml.dist
  .travis.yml
  README.md
  bin/create_pear_package.php
  composer.json
  docs/goals.md
  library/Requests.php
  package.xml.tpl
  tests/Proxy/HTTP.php
  tests/Utility/FilteredIterator.php
Labels: Type: breaking change, Type: meta

#490 Update all branch references
  .github/release-checklist.md
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
  README.md
  docs/why-requests.md
Labels: Type: meta

#488 Composer: enhance information
  composer.json
Labels: Type: documentation, Type: testing/chores/QA

#491 Add .editorconfig file
  .codecov.yml
  .editorconfig
  composer.json
Labels: Type: meta, Type: testing/chores/QA

#489 Documentation: link review
  CHANGELOG.md
  README.md
  docs/hooks.md
  docs/usage-advanced.md
  docs/usage.md
  docs/why-requests.md
  library/Requests.php
  library/Requests/IPv6.php
  library/Requests/IRI.php
  library/Requests/Transport/cURL.php
  library/Requests/Transport/fsockopen.php
  tests/IRI.php
  tests/SSL.php
Labels: Type: documentation

#446 Replace PHPUnit 6+ compat code with Yoast PHPUnit polyfills package
  .gitignore
  composer.json
  tests/Auth/Basic.php
  tests/ChunkedEncoding.php
  tests/Cookies.php
  tests/Encoding.php
  tests/IDNAEncoder.php
  tests/IRI.php
  tests/Proxy/HTTP.php
  tests/Requests.php
  tests/Response/Headers.php
  tests/SSL.php
  tests/Session.php
  tests/TestCase.php
  tests/Transport/Base.php
  tests/Transport/cURL.php
  tests/Transport/fsockopen.php
  tests/Utility/FilteredIterator.php
  tests/bootstrap.php
  tests/phpunit6-compat.php
Labels: Type: testing/chores/QA
