Repository WordPress/Requests, pull requests merged in 2021-08, with the labels that each got.

#508 Tests: only use our own autoloader when testing via a PHAR
  tests/bootstrap.php
Labels: Type: testing/chores/QA

#509 Drop support for HHVM
  library/Requests/Transport/fsockopen.php
Labels: Type: meta

#510 Clean up: remove previously deprecated methods
  examples/cookie.php
  library/Requests.php
  library/Requests/Cookie.php
  library/Requests/Cookie/Jar.php
Labels: Type: testing/chores/QA, Type: breaking change

#511 QA: tweak code coverage configuration
  .codecov.yml
Labels: Type: testing/chores/QA

#516 Add Roave security advisories for dev dependencies
  composer.json
Labels: Type: enhancement

#517 Composer: update version constraints
  composer.json
Labels: Type: testing/chores/QA

#379 Throw exception if invalid filename is provided
  library/Requests/Transport/cURL.php
  library/Requests/Transport/fsockopen.php
  tests/Transport/BaseTestCase.php
Labels: Component: Transports, Type: bug, Status: triage

#444 Removed CURLOPT_REFERER
  library/Requests/Transport/cURL.php
Labels: Component: Transports, Type: bug, Status: triage
