Repository WordPress/Requests, pull requests merged in 2021-11, with the labels that each got.

#583 GH Actions: more website update workflow tweaks
  .github/workflows/update-website.yml
Labels: Type: testing/chores/QA

#574 Auth\Basic: add input validation to constructor
  src/Auth/Basic.php
  src/Exception/ArgumentCount.php
  src/Proxy/Http.php
  tests/Auth/BasicTest.php
  tests/Exception/ArgumentCountTest.php
  tests/Proxy/HttpTest.php
Labels: Type: enhancement

#586 BC-layer: fix fatal "can not inherit from final class" errors
  composer.json
  library/Deprecated.php
  tests/AutoloadTest.php
Labels: Type: bug

#587 Rename interface Hooker => HookManager
  docs/upgrading.md
  src/Autoload.php
  src/Cookie/Jar.php
  src/HookManager.php
  src/Hooks.php
  src/Requests.php
Labels: Type: breaking change, Type: enhancement

#592 IdnaEncoder::encode(): add input validation
  src/IdnaEncoder.php
  tests/IdnaEncoderTest.php
Labels: Type: testing/chores/QA, Type: enhancement

#604 Class FilteredIterator: add input validation
  src/Utility/FilteredIterator.php
  tests/Utility/FilteredIteratorTest.php
Labels: Type: testing/chores/QA, Type: enhancement

#605 Response\Headers: add input validation + more defensive coding
  src/Response/Headers.php
  tests/Response/HeadersTest.php
Labels: Type: testing/chores/QA, Type: breaking change, Type: bug, Type: enhancement

#603 Class Response: improve input handling
  src/Response.php
Labels: Type: testing/chores/QA

#602 Class Iri: add input validation
  src/Iri.php
  tests/IriTest.php
Labels: Type: testing/chores/QA, Type: enhancement

#601 Class Ipv6: add input validation
  src/Ipv6.php
  tests/Ipv6Test.php
Labels: Type: testing/chores/QA, Type: enhancement

#606 Docblocks: update all `@package` tags
  src/Auth.php
  src/Auth/Basic.php
  src/Cookie.php
  src/Cookie/Jar.php
  src/Exception.php
  src/Exception/ArgumentCount.php
  src/Exception/Http.php
  src/Exception/Http/Status304.php
  src/Exception/Http/Status305.php
  src/Exception/Http/Status306.php
  src/Exception/Http/Status400.php
  src/Exception/Http/Status401.php
  src/Exception/Http/Status402.php
  src/Exception/Http/Status403.php
  src/Exception/Http/Status404.php
  src/Exception/Http/Status405.php
  src/Exception/Http/Status406.php
  src/Exception/Http/Status407.php
  src/Exception/Http/Status408.php
  src/Exception/Http/Status409.php
  src/Exception/Http/Status410.php
  src/Exception/Http/Status411.php
  src/Exception/Http/Status412.php
  src/Exception/Http/Status413.php
  src/Exception/Http/Status414.php
  src/Exception/Http/Status415.php
  src/Exception/Http/Status416.php
  src/Exception/Http/Status417.php
  src/Exception/Http/Status418.php
  src/Exception/Http/Status428.php
  src/Exception/Http/Status429.php
  src/Exception/Http/Status431.php
  src/Exception/Http/Status500.php
  src/Exception/Http/Status501.php
  src/Exception/Http/Status502.php
  src/Exception/Http/Status503.php
  src/Exception/Http/Status504.php
  src/Exception/Http/Status505.php
  src/Exception/Http/Status511.php
  src/Exception/Http/StatusUnknown.php
  src/Exception/InvalidArgument.php
  src/Exception/Transport.php
  src/Exception/Transport/Curl.php
  src/HookManager.php
  src/Hooks.php
  src/IdnaEncoder.php
  src/Ipv6.php
  src/Iri.php
  src/Port.php
  src/Proxy.php
  src/Proxy/Http.php
  src/Response.php
  src/Session.php
  src/Ssl.php
  src/Transport.php
  src/Transport/Curl.php
  src/Transport/Fsockopen.php
  src/Utility/CaseInsensitiveDictionary.php
  src/Utility/FilteredIterator.php
  src/Utility/InputValidator.php
Labels: Type: documentation

#594 Autoload: treat PSR-4 case-sensitively and PSR-0 case-insensitively
  src/Autoload.php
  tests/AutoloadTest.php
Labels: Type: testing/chores/QA

#588 Release checklist: minor tweaks
  .github/release-checklist.md
Labels: Type: documentation, Type: meta

#591 Ssl::verify_reference_name(): add more defensive coding
  src/Ssl.php
  tests/SslTest.php
Labels: Type: testing/chores/QA, Type: enhancement

#599 PHP 8.0 | Hooks::dispatch(): prevent potential fatal error
  src/Hooks.php
  tests/HooksTest.php
Labels: Type: enhancement

#595 DecompressionTest: improve tests
  src/Requests.php
  tests/EncodingTest.php
  tests/Requests/DecompressionTest.php
Labels: Type: testing/chores/QA, Type: enhancement

#608 Fix reports by PHPStan
  src/Cookie.php
  src/HookManager.php
  src/Hooks.php
  src/Port.php
  src/Requests.php
Labels: Type: documentation

#610 Cookie\Jar: add input validation
  src/Cookie/Jar.php
  tests/Cookie/JarTest.php
  tests/CookiesTest.php
Labels: Type: testing/chores/QA, Type: bug, Type: enhancement

#612 Session: rename magic method parameters
  src/Session.php
Labels: Type: testing/chores/QA

#609 Cookie: add input validation
  src/Cookie.php
  tests/CookiesTest.php
Labels: Type: testing/chores/QA, Type: enhancement

#613 Iri::__construct(): allow `$iri` to be stringable
  src/Iri.php
  tests/IriTest.php
Labels: Type: testing/chores/QA, Type: enhancement

#611 Proxy\Http::__construct(): add input validation
  src/Proxy/Http.php
  tests/Proxy/HttpTest.php
Labels: Type: testing/chores/QA, Type: enhancement

#614 IdnaEncoder + Ipv6: minor tweaks for Stringable support
  src/IdnaEncoder.php
  src/Ipv6.php
  tests/IdnaEncoderTest.php
  tests/Ipv6Test.php
Labels: Type: testing/chores/QA

#615 Ssl: safeguard support for Stringable objects
  src/Ssl.php
  tests/SslTest.php
Labels: Type: testing/chores/QA, Type: bug

#616 Requests::request(): use Capability constant
  src/Requests.php
Labels: Type: testing/chores/QA

#617 Requests: remove duplicate `match_domain()` method
  src/Requests.php
Labels: Type: testing/chores/QA

#618 CS/Docs: various minor fixes
  build/ghpages/UpdateMarkdown.php
  src/Cookie/Jar.php
  src/IdnaEncoder.php
  src/Requests.php
  src/Response/Headers.php
  src/Transport/Curl.php
  src/Transport/Fsockopen.php
  src/Utility/CaseInsensitiveDictionary.php
  tests/AutoloadTest.php
  tests/Transport/BaseTestCase.php
Labels: Type: testing/chores/QA

#620 Session: add input validation
  src/Session.php
  tests/SessionTest.php
Labels: Type: testing/chores/QA, Type: enhancement

#621 Requests: add input validation
  src/Requests.php
  tests/Requests/DecompressionTest.php
  tests/RequestsTest.php
Labels: Type: testing/chores/QA, Type: bug, Type: enhancement

#622 Update docs to provide context about CA list fallback
  docs/usage-advanced.md
Labels: Type: documentation

#623 CS: use short arrays
  .phpcs.xml.dist
  build/ghpages/update-docgen-config.php
  examples/basic-auth.php
  examples/cookie.php
  examples/get.php
  examples/multiple.php
  examples/post.php
  examples/proxy.php
  examples/timeout.php
  src/Auth/Basic.php
  src/Autoload.php
  src/Capability.php
  src/Cookie.php
  src/Cookie/Jar.php
  src/HookManager.php
  src/Hooks.php
  src/IdnaEncoder.php
  src/Ipv6.php
  src/Proxy/Http.php
  src/Requests.php
  src/Response.php
  src/Response/Headers.php
  src/Session.php
  src/Transport.php
  src/Transport/Curl.php
  src/Transport/Fsockopen.php
  src/Utility/CaseInsensitiveDictionary.php
  tests/Auth/BasicTest.php
  tests/AutoloadTest.php
  tests/Cookie/JarTest.php
  tests/CookiesTest.php
  tests/Exception/Http/StatusUnknownTest.php
  tests/Exception/HttpTest.php
  tests/Exception/Transport/CurlTest.php
  tests/Fixtures/ArrayAccessibleObject.php
  tests/Fixtures/RawTransportMock.php
  tests/Fixtures/TestTransportMock.php
  tests/Fixtures/TransportMock.php
  tests/HooksTest.php
  tests/IdnaEncoderTest.php
  tests/Ipv6Test.php
  tests/PortTest.php
  tests/Proxy/HttpTest.php
  tests/Requests/ChunkedEncodingTest.php
  tests/Requests/DecompressionTest.php
  tests/RequestsTest.php
  tests/Response/HeadersTest.php
  tests/ResponseTest.php
  tests/SessionTest.php
  tests/SslTest.php
  tests/TestCase.php
  tests/Transport/BaseTestCase.php
  tests/Transport/CurlTest.php
  tests/Transport/FsockopenTest.php
  tests/Utility/CaseInsensitiveDictionaryTest.php
  tests/Utility/FilteredIteratorTest.php
  tests/Utility/InputValidatorTest.php
Labels: Type: testing/chores/QA

#630 Docs: few more `@throws` tag order fixes
  src/Requests.php
  src/Response.php
  src/Session.php
  src/Transport/Fsockopen.php
Labels: Type: testing/chores/QA

#632 Update bundled certificates
  certificates/cacert.pem
Labels: Extras, Type: meta

#629 Transport\Curl/Fsockopen: add input validation
  src/Transport/Curl.php
  src/Transport/Fsockopen.php
  tests/Transport/BaseTestCase.php
Labels: Type: testing/chores/QA, Component: Transports, Type: enhancement

#634 GH Actions: no longer allow failures on PHP 8.1
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: Type: testing/chores/QA

#626 GH Pages/Actions: minor tweaks for the website generation
  .github/workflows/update-website.yml
  README.md
  docs/README.md
  docs/hooks.md
  phpdoc.dist.xml
Labels: Type: documentation

#640 Skip alternate port test while portquiz has issues
  tests/Transport/BaseTestCase.php
Labels: Type: testing/chores/QA

#642 Docs: minor tweak
  docs/README.md
Labels: Type: documentation
