Repository WordPress/Requests, pull requests merged in 2021-03, with the labels that each got.

#451 Update certificates file to latest version as of 2021-02-12
  library/Requests/Transport/cacert.pem
Labels: Transports

#456 Requests_Transport_cURL - fix PHP 8.0 issue with filename verification
  library/Requests/Transport/cURL.php
  tests/Transport/Base.php
Labels: Transports

#439 Travis: add build against PHP 8.0
  .travis.yml
Labels: Testing

#443 Add pagination to documentation pages
  docs/authentication-custom.md
  docs/authentication.md
  docs/goals.md
  docs/hooks.md
  docs/proxy.md
  docs/usage-advanced.md
  docs/usage.md
  docs/why-requests.md
Labels: Type: documentation
