Repository WordPress/Requests, pull requests merged in 2021-04, with the labels that each got.

#457 FilteredIterator: fix PHP 5.2/5.3 compatibility and actually run the tests
  library/Requests/Utility/FilteredIterator.php
  tests/Utility/FilteredIterator.php
  tests/phpunit.xml.dist
Labels: Type: testing/chores/QA

#464 CodeCov: add configuration
  .codecov.yml
  .coveralls.yml
Labels: Type: testing/chores/QA

#461 Travis: fix PHP 8.0 build
  .travis.yml
Labels: Type: testing/chores/QA

#458 Move the PHPUnit config file to the project root
  .travis.yml
  README.md
  composer.json
  phpunit.xml.dist
  tests/phpunit.xml.dist
Labels: Type: testing/chores/QA

#462 README: fix code blocks
  README.md
Labels: Type: documentation

#467 CI: switch to GitHub Actions for PHP 5.5 - current
  .codecov.yml
  .gitattributes
  .github/workflows/cs.yml
  .github/workflows/lint.yml
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
  composer.json
  tests/Proxy/HTTP.php
  tests/utils/proxy/start.sh
  tests/utils/proxy/stop.sh
Labels: Type: testing/chores/QA

#469 Manage "Expect" header with cURL transport
  library/Requests/Transport/cURL.php
  tests/Transport/cURL.php
Labels: Component: Transports

#465 Docs: update content and various tweaks to the markdown
  README.md
  docs/authentication-custom.md
  docs/authentication.md
  docs/goals.md
  docs/hooks.md
  docs/proxy.md
  docs/usage-advanced.md
  docs/usage.md
  docs/why-requests.md
Labels: Type: documentation

#471 Release 1.8.0
  CHANGELOG.md
Labels: Type: documentation, Type: meta

#477 Docs: various changes after site review
  README.md
  docs/README.md
  docs/authentication-custom.md
  docs/authentication.md
  docs/goals.md
  docs/hooks.md
  docs/proxy.md
  docs/usage-advanced.md
  docs/usage.md
  docs/why-requests.md
Labels: Type: documentation

#479 Changelog: minor link fix
  CHANGELOG.md
Labels: Type: documentation

#478 GH Pages: various minor tweaks to the content
  api/class-Requests_Exception.html
  docs/authentication-custom.md
  docs/authentication.md
  docs/goals.md
  docs/hooks.md
  docs/index.md
  docs/proxy.md
  docs/usage-advanced.md
  docs/usage.md
  docs/why-requests.md
  download/index.md
  index.md
  support/index.md
Labels: Type: documentation

#481 Docs: use https for own site links
  README.md
  docs/README.md
Labels: Type: documentation

#482 GH Pages: update some links
  _layouts/documentation.html
  _layouts/home.html
  _layouts/page.html
  docs/index.md
  index.md
Labels: Type: documentation
