Repository WordPress/Requests, pull requests merged in 2022-02, with the labels that each got.

#674 Composer: update branch name for test server
  composer.json
Labels: Type: testing/chores/QA

#662 GH Actions: version update for `codecov/codecov-action`
  .github/workflows/test.yml
Labels: Type: testing/chores/QA

#661 GH Actions: version update for `ramsey/composer-install`
  .github/workflows/cs.yml
  .github/workflows/lint.yml
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
Labels: Type: testing/chores/QA

#672 GH Actions: secure the website update workflow
  .github/workflows/update-website.yml
Labels: Type: testing/chores/QA

#669 GH Actions: add new workflow to auto-update certificate bundle
  .github/release-checklist.md
  .github/workflows/update-cacert.yml
  .gitignore
  certificates/cacert.pem.sha256
Labels: Type: testing/chores/QA

#671 Tests: fix incorrect class/file name for test class
  tests/CookieTest.php
Labels: Type: testing/chores/QA

#653 GH Pages / Release workflow improvements
  .github/release-checklist.md
  .github/workflows/update-website.yml
  build/ghpages/update-docgen-config.php
Labels: Type: documentation, Type: testing/chores/QA

#647 Hooks: priority should be respected
  src/Hooks.php
  tests/HooksTest.php
Labels: Type: bug

#646 Docs: full review of Hook documentation
  docs/hooks.md
Labels: Type: documentation

#676 Add change log entry for 2.0.1 release
  CHANGELOG.md
  src/Requests.php
Labels: Type: documentation

#677 Release 2.0.1
  .github/release-checklist.md
  .github/workflows/cs.yml
  .github/workflows/lint.yml
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
  .github/workflows/update-cacert.yml
  .github/workflows/update-website.yml
  .gitignore
  .phpcs.xml.dist
  CHANGELOG.md
  build/ghpages/UpdateMarkdown.php
  build/ghpages/update-docgen-config.php
  certificates/cacert.pem
  certificates/cacert.pem.sha256
  composer.json
  docs/hooks.md
  src/Cookie.php
  src/Hooks.php
  src/IdnaEncoder.php
  src/Ipv6.php
  src/Iri.php
  src/Proxy/Http.php
  src/Requests.php
  src/Response.php
  src/Session.php
  src/Transport/Curl.php
  src/Transport/Fsockopen.php
  tests/CookieTest.php
  tests/Fixtures/TestTransportMock.php
  tests/Fixtures/TransportMock.php
  tests/HooksTest.php
  tests/RequestsTest.php
  tests/SslTest.php
  tests/Transport/BaseTestCase.php
  tests/bootstrap.php
Labels: Type: meta

#684 QA: minor whitespace fixes
  src/Exception/Transport/Curl.php
  src/Requests.php
  tests/Fixtures/RawTransportMock.php
  tests/Fixtures/TestTransportMock.php
  tests/HooksTest.php
Labels: Type: testing/chores/QA

#682 QA: use static closures
  build/ghpages/update-docgen-config.php
  tests/AutoloadTest.php
  tests/HooksTest.php
  tests/bootstrap.php
Labels: Type: testing/chores/QA

#681 Autoload: introduce method `get_deprecated_classes()`.
  examples/preload-aliases.php
  src/Autoload.php
  tests/AutoloadTest.php
Labels: Type: enhancement, Status: triage

#688 GH Actions: update the setup-python action
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
Labels: Type: testing/chores/QA

#667 Support proxy in Requests::request_multiple()
  src/Transport/Curl.php
  tests/Proxy/HttpTest.php
Labels: Component: Transports, Type: bug

#689 Refine docs for `curl.before_send`
  docs/hooks.md
Labels: Type: documentation

#316 Add tests for 303 status code
  tests/Transport/BaseTestCase.php
Labels: Type: testing/chores/QA

#690 Revert "Skip alternate port test while portquiz has issues"
  tests/Transport/BaseTestCase.php
Labels: Type: testing/chores/QA
