Repository WordPress/Requests, pull requests merged in 2023-06, with the labels that each got.

#810 Changelog for release 2.0.7
  CHANGELOG.md
  src/Requests.php
Labels: Type: documentation, Type: meta

#813 Add `security.md` file
  .github/SECURITY.md
Labels: Type: documentation

#815 Replace Heroku test-server with Render alternative
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
  tests/EnvironmentTest.php
  tests/bootstrap.php
Labels: Type: testing/chores/QA
