Repository WordPress/Requests, pull requests merged in 2024-06, with the labels that each got.

#870 CS: always clarify operator precedence when mixing boolean operators
  src/IdnaEncoder.php
  src/Ipv6.php
Labels: Type: testing/chores/QA

#871 Tests: fix PHPUnit deprecation notices
  tests/Cookie/Jar/NormalizeCookieTest.php
  tests/Cookie/NormalizeTest.php
  tests/Cookie/PathMatchesTest.php
  tests/Cookie/UriMatchesTest.php
  tests/Exception/Http/StatusCodeTest.php
  tests/Response/IsRedirectTest.php
  tests/TypeProviderHelper.php
Labels: Type: testing/chores/QA

#874 Add testing proxy temporary files to .gitignore
  .gitignore
Labels: Type: testing/chores/QA, Type: meta

#847 Allow integers as cookie names
  src/Cookie.php
  tests/Cookie/ConstructorTest.php
  tests/Cookie/ParseTest.php
Labels: Type: bug

#875 GH Actions/test: use the latest Python version for mitmproxy
  .github/workflows/quicktest.yml
  .github/workflows/test.yml
Labels: Type: testing/chores/QA
